frontend:
	bash components/frontend.sh

cart:
	bash components/cart.sh

catalogue:
	bash components/catalogue.sh		

mongodb:
	bash components/mongodb.sh

redis:
	bash components/redis.sh	

user:
	bash components/user.sh